# .streamlit/secrets.toml
[MONGODB_URI]
uri = "mongodb+srv://JesusHdzzzz:oHTmFdBV249fCJMP@cluster0.tlrpp.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

[GEMINI_API_KEY]
api_key = "AIzaSyDwVFHhjS6X8wxoLmFgi7Y4oq2gPBEatMY"